$(document).ready(function(){
    $("button").click(function(){
        alert("hello");
        $("#demo").css("background-color","yellow");
        $("#demo1").css("background-color","red");
        $("#demo2").css("borderBottomColor","blue");
        $("#demo3").css("borderBottomColor","blue");
    });
});